name: Route53 DNS
description: |
  Rancher External DNS service powered by Amazon Route53
<<<<<<< HEAD
version: v0.6.4.1
=======
version: v0.6.3
>>>>>>> upstream/v1.6.1-rc4
category: External DNS
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,mesos,swarm,kubernetes'
